version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: skymarket
      POSTGRES_PASSWORD: skymarket
      POSTGRES_DB: skymarket
    restart: always
    ports:
    - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U skymarket" ]
      interval: 10s
      timeout: 5s
      retries: 5


  frontend:
    build: ../frontend_react/.
    volumes:
      - frontend:/app/build
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ../skymarket/django_static/:/usr/share/nginx/html/django_static/
      - ../skymarket/django_media/:/usr/share/nginx/html/django_media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend:/usr/share/nginx/html/
    restart: always
    depends_on:
      - db
      - frontend

  backend:
    build: ../skymarket/.
    volumes:
      - ../skymarket/:/app/
      - ../skymarket/django_static/:/app/static/
      - ../skymarket/django_media/:/app/media/
    ports:
      - "8008:8000"
    depends_on:
      - db
      - frontend
      - nginx

volumes:
  postgres_data:
  frontend:
